-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfbvrU6br/yd3KWev
YRimsrmWqjCXdCtCrh7cVwWlP/ygCgYIKoZIzj0DAQehRANCAAQ2buCOOgU5Maw8
SmYVw0UJBZ7JzPpM0ss0l7YP4UyMu15okJySnU8ICPJErDVIZNFWGelkc0QIoFWe
jh0hPOnO
-----END PRIVATE KEY-----